### ISSUE TITLE
How many combinations could be there ?

### ISSUE THREAD

**Issue by sahanDissanayake** [TheDeveloper/sillyname#3]
Hi @TheDeveloper ,

I'm gonna use this as this is very much similar the the functionality on Google Docs when someone comes up online.

Im not too sure how to count the max number of combinations there could be... Didn't pass my math very well ha ha :disappointed: 

Do you know how many there could be please ?

**Comment by meaniostack** [comment]
364 nouns
527 adjectives

nouns*nouns*adjectives = amount of possibilities
364*364*527 = 69,825,392 possibilities

**Comment by sahanDissanayake** [comment]
God damn son :+1: :star2: 

Awesome
